CREATE USER grupo3 WITH PASSWORD '1234';
CREATE DATABASE main OWNER grupo3;
GRANT ALL PRIVILEGES ON DATABASE main TO grupo3;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO grupo3;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO grupo3;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO grupo3;

